apiVersion: v1
kind: Service
metadata:
  name: affinity-tester
spec:
  type: LoadBalancer
  ports:
  - name: test-port
    port: 56789
    protocol: UDP
  selector:
    app: affinity-tester
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
